### ISSUE TITLE
Create A README for array section.

### ISSUE THREAD

**Issue by sPredictorX1708** [dubesar/JavaScriptEssentials#1]
Currently, the Array folder only contains different methods in an array and also some ways to manipulate. Add in a proper readme mentioning details of each file in the folder. Keep it brief so that it is easily explainable. For any doubt ping me so that I can explain the structure of the readme.

**Comment by neupanedipen** [comment]
Can i take care of this?

**Comment by sPredictorX1708** [comment]
@neupanedipen yes if  you have any doubts ping me

**Comment by neupanedipen** [comment]
Sure. Can you assign this to me?

**Comment by sPredictorX1708** [comment]
ok am assigning it to you

**Comment by neupanedipen** [comment]
Great. Where can I ping you btw?

**Comment by sPredictorX1708** [comment]
@neupanedipen you can ping me here only
