### ISSUE TITLE
Create A README for Loops section

### ISSUE THREAD

**Issue by sPredictorX1708** [dubesar/JavaScriptEssentials#2]
Currently, the Loops folder only contains different methods to implement Loops in JS and also some ways to manipulate do some operations. Add in a proper readme mentioning details of each file in the folder. Keep it brief so that it is easily explainable. For any doubt ping me so that I can explain the structure of the readme.

**Comment by bhattaraib58** [comment]
@dubesar  can i take it ?? and can you assign this task to me ?

**Comment by sPredictorX1708** [comment]
@bhattaraib58 please go ahead and take it.
