### ISSUE TITLE
Create A README for Conditionals section. 

### ISSUE THREAD

**Issue by sPredictorX1708** [dubesar/JavaScriptEssentials#3]
Currently, the Conditionals folder only contains different methods to implement conditions in JS and also some ways to manipulate do some operations. Add in a proper readme mentioning details of each file in the folder. Keep it brief so that it is easily explainable. For any doubt ping me so that I can explain the structure of the readme.

**Comment by Rishabh3321** [comment]
Can I take up this issue:: Updating Readme for conditionals?  
I have in-depth knowledge of Javascript. Please specify the format you want to have in this repository.

**Comment by Rishabh3321** [comment]
We can even extend the react folder further to hooks.
I have been working with hooks for a long time and can contribute on that part too.
How about this suggestion?

**Comment by sPredictorX1708** [comment]
@Rishabh3321 sure please help in any form that you can, I will review your PR.

**Comment by sPredictorX1708** [comment]
> Can I take up this issue:: Updating Readme for conditionals?
> I have in-depth knowledge of Javascript. Please specify the format you want to have in this repository.

You can refer to array folder README format.
